apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:  # Corrected from "macthLabels"
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:  # Corrected indentation for "containers"
      - name: spring
        image: jingnin/spring-img
        ports:
          - containerPort: 8080
